[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"

# Netlify Functions configuration
[functions]
  # Directory for Netlify Functions
  directory = ".netlify/functions-internal/"

[[functions]]
  # Apply timeout to all functions (max 26 seconds for Pro plans, 10s for free)
  function = "*"
  timeout = "26s"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=86400"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle client-side routing (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance optimizations
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"